### ISSUE TITLE
Data loss during conversion from `Model` to `Schema`? (timestamps)

### ISSUE THREAD

**Issue by bsieber-mozilla** [mozilla-it/ctms-api#611]
https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/acoustic_service.py#L248-L250

Unless the `update_timestamp` field is null in the contact.newsletter, this field might never update with the current logic (to reuse the prior timestamp).

I believe the `update_timestamp` field should be updated when a contact is updated.

---
The [NewsletterSchema](https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/acoustic_service.py#L224) doesn't have the timestamps (_[but do exist on the model)](https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/models.py#L96-L117)_--so, I assume, the timestamps are currently always updated to be the same value of "_today"?

During the conversion from model.Email to schema.ContactSchema--are we losing the timestamp information as well?

`(some) Models have timestamps -> (some) Schemas appear to not have timestamps`

**Comment by bsieber-mozilla** [comment]
Entry for getting contact data in `acoustic_sync` process:
 https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/sync.py#L67-L70
 
Which can be found here:
 https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/crud.py#L362-L368

it calls this method which uses the Email model to build the ContactSchema:
https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/crud.py#L179-L194

---

Should we have additional schema models with timestamps?

_Maybe I'm missing something?_
---

**Comment by leplatrem** [comment]
My initial understanding was that schemas were used to validate input data. It thus makes sense for them not to have the timestamps since they are meant to be provided by the clients on input.

But when working on #609, I was surprised to see that schema instances were used as parameter of things like:

https://github.com/mozilla-it/ctms-api/blob/c3d3223216007cd987bc9868fa9189e69a41ef81/ctms/acoustic_service.py#L141-L146

Introduced in parts in https://github.com/mozilla-it/ctms-api/pull/181

> Should we create additional schema models with create/update timestamps?

Or what would be the consequence of using model instances down the line in Acoustic sync, instead of schema instances?

**Comment by bsieber-mozilla** [comment]
> Or what would be the consequence of using model instances down the line in Acoustic sync, instead of schema instances?

I think that would be worth investigating. It looks like #181 might've used the wrong objects for this sync..
