### ISSUE TITLE
Make sure we're doing sessions correctly

### ISSUE THREAD

**Issue by imbstack** [mozilla-it/ctms-api#70]
https://docs.sqlalchemy.org/en/13/orm/contextual.html

**Comment by jwhitlock** [comment]
I think the change is to use a ``scoped_session``, as suggested by the docs, which will ensure that a new ``Session`` is generated for each thread.

**Comment by jwhitlock** [comment]
We're seeing issues in production that we haven't seen in staging or development, so we probably did it the wrong way 😢 

* In ``sqlalchemy/orm/session.py``, ``_connection_for_bind``: ``self.session`` is None
* In ``sqlalchemy/orm/session.py``, ``_assert_active``: ``InvalidRequestError`` raised because "This session is in 'prepared' state; no further SQL can be emitted within this transaction"
* In ``sqlalchemy/orm/strategies.py``, ``_load_for_state``: ``DetachedInstaceError`` raised because "Parent instance is not bought to a session, lazy load operation ... cannot proceed" (http://sqlalche.me/e/13/bhk3)
* In ``sqlalchemy/orm/session.py``, ``_assert_active``: ``ResourceClosesError`` raised because "This transaction is closed"

and a few others

**Comment by jwhitlock** [comment]
This [comment](https://github.com/tiangolo/fastapi/issues/726#issuecomment-584371305) suggests ``scoped_session`` is a bad fit for FastAPI:

> SQLAlchemy scoped_session is based on thread locals. As (*a user*) points out, those are not mapped 1:1 to requests when using async stuff. In summary, a single thread can handle more than one request, and at the same time, a single request could be handled by more than one thread (so it's actually not 1:1 but many:many). The alternative would be ContextVars, those are made to solve these use cases. But they don't behave exactly the same as thread locals and there are some caveats.

The exceptions could be caused by reusing sessions that were previously released. I think reverting PR #117 will fix the issues.

**Comment by jwhitlock** [comment]
Removing `scoped_session` worked in production with gunicorn.
